### PR TITLE
Test/ Sproll EVM prover

### PR DESCRIPTION
**Pull request by naure**
This PR contains configuration that can prove the [sproll-evm executable](https://github.com/scroll-tech/sproll-evm/pull/60/files#diff-0e528863de23811e1d04049eccabd887e785625f5f0fe7381122cfeeba24960d).

```
RUST_LOG=info,e2e=debug,ceno_emul=debug,ceno_zkvm::scheme=warn MOCK_PROVING=1
cargo run --package ceno_zkvm --bin e2e --release -- --platform=sp1 --max-steps=10000  riscv32im-succinct-zkvm-elf
```

(remove `--max-steps` for the full run)

Warning: ecalls WRITE, COMMIT, and COMMIT_DEFERRED_PROOFS are replaced with NOP.

### CODE REVIEW

**Review by lispc — APPROVED** [review]
seems good.   I guess configs of some other tests may not work well with new default values.  So ok to merge after CI fixed.

**Comment by hero78119** [comment]
Hi @naure a quick question: does this configuration also works for https://github.com/sp1-patches/revm ? probably we can plan to give a try + @zemse

**Comment by naure** [comment]
> Hi @naure a quick question: does this configuration also works for https://github.com/sp1-patches/revm ? probably we can plan to give a try + @zemse

Yes --> https://github.com/scroll-tech/ceno/issues/641

**Comment by naure** [comment]
@lispc Fixed to cover existing tests too.

**Pull request merged**
