### PR TITLE
fix/program-size4: fix padding in edge cases

### PR DESCRIPTION
**Pull request by naure**
This bug was fixed then broken again in a cleanup attempt. 🤦 

Note that the whole topic is being refactored in #624 so hopefully we won’t have this issue anymore.

### CODE REVIEW

**Review by mcalancea — APPROVED** [review]

**Review by hero78119 — CHANGES_REQUESTED** [review]
Sorry I disable auto merge because I was thinking to identify the root cause instead of quick patching 😃 .

question, does the number of instance size different with real padding just exist to deal with program table special case?

**Comment by naure** [comment]
Yes at the moment this problem only exists the program table because it has a separate configuration of max size versus content. In other places (e.g. `NonVolatileTableConfig`) we just required an exact match.

Although you’re right that there is a more elegant fix which is to require a tight fit of the size. This wasn’t possible in the original fix because the size was not configurable yet. Let me try that.

**Comment by matthiasgoergens** [comment]
Thanks for trying to fix this.

Could we please add a test that would fail if/when this break again?

**Comment by naure** [comment]
Better not introduce this problem in the first place: #638

**Pull request closed without merging**
