### PR TITLE
Match emulator to circuits: use a Harvard Architecture

### PR DESCRIPTION
**Pull request by matthiasgoergens**
Our circuits use a [modified](Modified_Harvard_architecture) [Harvard architecture](https://en.wikipedia.org/wiki/Harvard_architecture) where the memory space for instructions and data are completely separated, even though they are both addressed with 32 bits.  That is a Good Thing.

That means writing to the data cell with address x does not change the value of the instruction cell with address x.

In contrast, our emulator uses a [von Neumann architecture](https://en.wikipedia.org/wiki/Von_Neumann_architecture) at its core, but goes through quite a few gymnastics to hide that fact.

> In a von Neumann architecture, data memory and stored program memory are intermixed.  Modern computers have moved away from this architecture for [security](https://en.wikipedia.org/wiki/W%5EX) and performance reasons.

In this PR, we turn our emulator into a Harvard Architecture machine as well to match what our circuits are doing.  That means we change the emulator to explicitly load instructions not from the data RAM, but from the program ROM, which we are already storing separately anyway.

> Instead of thinking about separate address spaces for data and code, you can also imagine that we have an [instruction cache and a data cache](https://en.wikipedia.org/wiki/Modified_Harvard_architecture#Split-cache_(or_almost-von-Neumann)_architecture), and that we load the instructions into their cache once at the start of the program, and then never invalidate that cache.

This works towards https://github.com/scroll-tech/ceno/issues/630

### CODE REVIEW

**Comment by icemelon** [comment]
Since you change the emulator to Harvard Architecture, should you also update the memory address space [here](https://github.com/scroll-tech/ceno/blob/master/ceno_emul/src/platform.rs#L21-L28)?

**Comment by icemelon** [comment]
Is this PR ready for review? I see there're many todos left

**Comment by matthiasgoergens** [comment]
> Since you change the emulator to Harvard Architecture, should you also update the memory address space [here](https://github.com/scroll-tech/ceno/blob/master/ceno_emul/src/platform.rs#L21-L28)?

Well, we could just totally remove the whole ROM section, because there's no problem with executing code anywhere, now that we separated the address spaces.  But I want to keep this PR as small as possible, and there's also no immediate problem with keeping the ROM section contained, either.  Or am I missing something?

> Is this PR ready for review? I see there're many todos left

The TODOs are for future work, I want to keep this PR small.  (I can convert them into issues, too, if you think that's better, but for these small organisational items I prefer to have them discoverable in the code.)

**Comment by matthiasgoergens** [comment]
@icemelon Let me make the follow up PR quickly that addresses the TODOs.  Think of this PR as pre-emptively extracted from the big PR the TODOs hint at.  Smaller PRs are easier to review and get consensus on.

**Review by lispc — APPROVED** [review]
lgtm

**Comment by icemelon** [comment]
> there's also no immediate problem with keeping the ROM section contained, either.
@matthiasgoergens Yes, you're right. I was thinking of having different memory space for ROM and RAM. But it's not necessary.

**Comment by lispc** [comment]
> writing to the data cell with address x does not change the value of the instruction cell with address x

I think this pr finishes what it claims to do "writing to the data cell with address x does not change the value of the instruction cell with address x,  so make emulator be consistent with prover".

the TODOs are good refactor, but not directly part of this purpose.  So i think it is ok now.

**Comment by matthiasgoergens** [comment]
> I don't mind making PR small. But why not finish the implementation of the Hardvard architecture emulator in this PR? I don't think it will make the pr too large. But I'll leave this up to @lispc

This PR finishes the Harvard architecture.  The TODOs are for cleanup enabled by the switch.

**Pull request merged**
